Convert from use of bashrc directories to list of users sourced. Support USERS dir. Simplified to use only files found in either ~ or $BASHRC/USERS.

diff --git a/bash-init b/bash-init
--- a/bash-init
+++ b/bash-init
@@ -8,36 +8,56 @@
 # Normally not used, but if used must not be propagated!
 unset BASH_ENV
 
-# POSIX requires this but for safety ...
-export LOGNAME=${LOGNAME:-$(logname)}
-
+# Find the config files to be sourced.
 export BASHRC=${BASH_SOURCE[0]%/*}
+if [[ "$*" == *-user=* ]]; then
+    # Source standard/versioned config files of specified user.
+    for arg in "$@"; do
+	if [[ $arg == -user=* ]]; then
+	    eval ${arg#-}
+	    break
+	fi
+    done
+    topshell=$BASHRC/USERS/$user/topshell
+    pershell=$BASHRC/USERS/$user/pershell
+    if [[ ! -f $topshell ]]; then
+	echo "Error: no init files in ${topshell%/*}" >&2
+	return 2
+    fi
+else
+    user=${LOGNAME:-$(logname)}
+    topshell=~/.bash-topshell
+    pershell=~/.bash-pershell
+fi
 
-[[ ! -r $BASHRC/func/pathfuncs ]] || source $BASHRC/func/pathfuncs
+# These functions can be used in setting up PATH variables.
+source $BASHRC/func/pathfuncs
 
 #####################################################################
 # Exported settings belong in ~/.bash-topshell
 #####################################################################
-topshell=${BASHRC%/*}/.bash-topshell
-if [[ "$BASH_INIT_BY" != "$LOGNAME" ]]; then
+if [[ "$BASH_INIT" != *$user* ]]; then
     # Use "source $BASHRC/bash-init -reset" to force an initial PATH setting
     if [[ "$*" == *-reset* ]]; then
+	unset BASH_INIT
 	PATH=/bin:/usr/bin
+	[[ ! -r /etc/profile ]] || source /etc/profile
     fi
 
-    #echo "INITIALIZING ENVIRONMENT SETTINGS in $$ FROM $topshell" >&2
+    [[ "$*" != *-debug* ]] || echo "INITIALIZING ENVIRONMENT SETTINGS in $$ FROM $topshell" >&2
     source $topshell
+
+    cleanpath PATH
+
+    export BASH_INIT=${BASH_INIT:+$BASH_INIT:}$user
 fi
-unset topshell
 
 #####################################################################
 # Interactive settings belong in ~/.bash-pershell
 #####################################################################
-pershell=${BASHRC%/*}/.bash-pershell
 if [[ "$*" == *-pershell* && -f $pershell ]]; then
-    #echo "INITIALIZING INTERACTIVE SETTINGS IN $$ FROM $pershell" >&2
+    [[ "$*" != *-debug* ]] || echo "INITIALIZING INTERACTIVE SETTINGS in $$ FROM $pershell" >&2
     source $pershell
 fi
-unset pershell
 
-export BASH_INIT_BY=$LOGNAME
+unset topshell pershell user
